# Generated by Django 3.1.5 on 2021-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('writter', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
            ],
        ),
    ]
