# Generated by Django 3.1.5 on 2021-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210305_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planguage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
